# Generated by Django 5.2.7 on 2025-10-14 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='lasname',
            new_name='lastname',
        ),
    ]
